Rename workflow files
Co-authored-by: Jessica Chang <jesschang77@gmail.com>
Co-authored-by: Andrew Moore <andrewdmoore84@gmail.com>

diff --git a/templates/delete_preview_app.yml b/templates/delete_preview_app.yml
--- a/templates/delete_preview_app.yml
+++ b/templates/delete_preview_app.yml
@@ -1,34 +1,26 @@
-name: Remove Preview Apps For Pull Request
+name: Remove Preview App AWS Resource Set
 
 on:
-  pull_request:
-    types: [closed]
   workflow_dispatch:
     inputs:
-      pr-number:
-        require: true
-        type: number
-
-env:
-  REPO_NAME_WITH_OWNER: ${{ github.repository }}
-  REPO_NAME: ${{ github.event.repository.name }}
+      bucket:
+        required: true
+        type: string
+      distro:
+        required: true
+        type: string
+      lambda:
+        required: true
+        type: string
 
 jobs:
-  delete:
+  delete-resource-set:
     runs-on: ubuntu-latest
     env:
       AWS_ACCESS_KEY_ID: ${{ secrets.BUBBLE_AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.BUBBLE_AWS_SECRET_ACCESS_KEY }}
       AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
     steps:
-      - name: Set env vars when workflow is initiated by PR closing
-        run: |
-          echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV
-        if: ${{ !inputs.pr-number }}
-      - name: Set env vars when workflow is initiated by bubble destroy
-        run: |
-          echo "PR_NUMBER=${{ inputs.pr-number }}" >> $GITHUB_ENV
-        if: ${{ inputs.pr-number }}
       - name: Missing AWS Credentials
         if: ${{ !env.AWS_SECRET_ACCESS_KEY && !env.AWS_ACCESS_KEY_ID }}
         run: exit 1
@@ -37,46 +29,21 @@ jobs:
           aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
-      - name: Get branch name
-        id: branch-name
-        uses: tj-actions/branch-names@v5.4
-      - name: Retrieve commits
-        uses: mathiasvr/command-output@v1
-        id: previewappdata
-        with:
-          run: |
-            aws dynamodb get-item --table-name ${{ env.REPO_NAME }}-PreviewApps --key '{ "PullRequestId": {"N": "${{ env.PR_NUMBER }}"}}'
-      - name: Parse commits to get AWS Resource IDs
-        uses: satackey/action-js-inline@v0.0.2
-        id: getbundles
-        with:
-          script: |
-            const core = require('@actions/core')
-
-            const pullRequestObj = ${{ steps.previewappdata.outputs.stdout }}
-            const commitsArray = pullRequestObj.Item.Commits.L
-
-            const bundles = []
-
-            commitsArray.forEach(commit => {
-              const bucketId = commit.M.BucketId.S
-              const distro = commit.M.CloudFrontDistroId.S
-              const lambdaPrefix = bucketId.split('-')[0]
-              const branchName = "${{ steps.branch-name.outputs.current_branch }}"
-
-              const command = `"gh workflow run delete_bundle.yml -f bucket=${bucketId} -f distro=${distro} -f lambda=${lambdaPrefix} --repo ${{ env.REPO_NAME_WITH_OWNER }} -r ${branchName}"`
-              bundles.push(command)
-            });
-
-            core.setOutput('bundles', bundles.join("\n"))
-      - name: Delete AWS resources for each commit
+      - name: Delete s3 bucket
+        run: aws s3 rb s3://${{ inputs.bucket }} --force || echo "Bucket ${{ inputs.bucket }} could not be deleted" && continue
+      - name: Delete Cloudfront distribution id
         run: |
-          myarray=(${{ steps.getbundles.outputs.bundles }})
-          for (( i=0; i<=${#myarray[@]}; i++ )); do
-            ${myarray[$i]}
-          done
-        env:
-          GITHUB_TOKEN: ${{ secrets.BUBBLE_GITHUB_TOKEN }}
-      - name: Soft delete pull request entry in DynamoDB
+          sudo apt-get update
+          sudo apt-get -y install jq
+          aws cloudfront get-distribution-config --id ${{ inputs.distro }} | jq .DistributionConfig.Enabled=false > tmp.json
+          jq -r .DistributionConfig tmp.json > tmp2.json
+          aws cloudfront update-distribution --id ${{ inputs.distro }} --if-match $(jq .ETag tmp.json -r) --distribution-config file://tmp2.json
+          aws cloudfront wait distribution-deployed --id ${{ inputs.distro }}
+          aws cloudfront delete-distribution --id ${{ inputs.distro }} --if-match $(aws cloudfront get-distribution-config --id ${{ inputs.distro }} | jq .ETag -r)
+      - name: Delete all Lambdas
         run: |
-          aws dynamodb update-item --table-name ${{ env.REPO_NAME }}-PreviewApps --key '{ "PullRequestId": {"N": "${{ env.PR_NUMBER }}"}}' --update-expression "SET IsActive = :val" --expression-attribute-values '{":val":{"BOOL":false}}' --return-values ALL_NEW
+          FUNCTIONS=$(aws lambda list-functions --region us-east-1 --query "Functions[?starts_with(FunctionName, '${{ inputs.lambda }}')].FunctionName" --output text)
+          for FUNCTION in $FUNCTIONS
+            do
+              aws lambda delete-function --function-name $FUNCTION || echo "Lambda function $FUNCTION could not be deleted" && continue
+            done
